### ISSUE TITLE
Allow scalar values

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/NIR#12]
The present formalism insists on full tensor representations to disambiguate shape. We should consider allowing a shorthand notation to allow defining scalars, but then require the shape to be defined. Something like

```python
nir.Linear(weights=1, bias=0, shape=(10, 10))
```

vs. the complete present formulation
```python
nir.Linear(weights=np.ones(10, 10), bias=np.ones(10))
```

**Comment by stevenabreu7** [comment]
I don't think this is necessary - since NIR is just an intermediate representation, we don't need to define the most convenient API for use cases that will likely be rare (typically one already has access to the full weight matrix when converting to a NIR graph). 

Can we close this @Jegp?

**Comment by Jegp** [comment]
Sure, that makes sense. I do think we should care about usability. But not for now :)
