### ISSUE TITLE
Add sensible defaults to neuron models

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/NIR#13]
Currently, the neuron models require complete specification of the primitives. For usability, we could consider setting default values for some variables.

For the `LIF` spec we could, for instance, set `v_threshold=1`, `v_leak=0`, and `r=1`. Currently, 

- [ ] LI
- [ ] LIF
- [ ] IF
- [ ] Conv1d
- [ ] Conv2d

**Comment by stevenabreu7** [comment]
Same comment as #12 - I'm not sure this is necessary for an intermediate representation. Do you still think we should implement this? @Jegp

**Comment by matjobst** [comment]
I would agree with @stevenabreu7 and think it is unnecessary as NIR is not meant as end-user product.
In most cases, these would anyways have to be changed from the default (even if only to adapt to the correct shapes).

**Comment by Jegp** [comment]
Agree with you both. I recall this was a conversation at Telluride at some point to make NIR more usable, but that's definitely not on the top priority now.
