### ISSUE TITLE
Collapse linearities

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/NIR#14]
Two linearities in sequence can, in theory, be collapsed by a matrix multiplication (if we get rid of the bias term).
However, this is only desirable when the resulting matrix doesn't get too big!

**Comment by stevenabreu7** [comment]
I don't think there's anything for us to do here right? imo, it's fine to just leave it up to the user - if they want to do two linearities in sequence, that's what'll happen and we won't collapse it for them (in WYSIWYG spirit, to avoid unexpected behavior)
