### ISSUE TITLE
Generate meaningful names with from_list()

### ISSUE THREAD

**Issue by matjobst** [neuromorphs/NIR#20]
We could create more meaningful names instead of using the index as name:
For example similar to how Tensorflow handles that: It uses the type of node to create the names. For example:
The first instance of Dense will be called "dense", the second "dense_1" etc.

**Comment by Jegp** [comment]
I see how it would make sense to have more meaningful names via the `from_list` constructor.

I'm not sure I'm a fan of the indexing, though. Doesn't that imply there is an ordering based on each node *type*? That `dense` comes before `dense_1`?

What about retaining the index across node types? Given the graph is constructed from a list, wouldn't it make sense to have a graph `Linear -> Linear` look like this? `Input_0` -> `Linear_1` -> `Linear_2` -> `Output_3`?

Concretely, it could look something like this:
```python
return NIRGraph(
    nodes={f"{type(n).__name__}_{str(i)}": n for i, n in enumerate(nodes)},
    edges=[(str(i), str(i + 1)) for i in range(len(nodes) - 1)],
)
```

**Comment by matjobst** [comment]
Thank you for your proposal, that is of course another option. That has the nice benefit of not requiring a per-node-type counter.

However, it might also get confusing if you have a graph Dense->LIF->Dense. Then you would have `Input_0`->`Dense_1`->`LIF_2`->`Dense_3`->`Output_4`, with `Dense_1` and `Dense_3`, but no `Dense_2`.

In the Tensorflow-like naming, that would be `input`->`dense`->`lif`->`dense_1`->`output`.

I do not see the ordering implication as an issue here. But maybe that is also because I am used to the way Tensorflow does the default naming. Also this default naming is only for the from_list which can only create a sequential graph, giving a deterministic naming.

Addendum: In your proposal the edges also need the changed names :)
return NIRGraph(
    nodes={f"{type(n).__name__}_{str(i)}": n for i, n in enumerate(nodes)},
    edges=[(f"{type(nodes[i]).__name__}_{str(i)}", f"{type(nodes[i+1]).__name__}_{str(i)}") for i in range(len(nodes) - 1)],
)

**Comment by Jegp** [comment]
I honestly don't have strong opinions here. I can see both systems working. If you're happy with the Tensorflow style, I would be fine to sign off on that :-)
