### ISSUE TITLE
Support nir.__version__

### ISSUE THREAD

**Issue by matjobst** [neuromorphs/NIR#24]
Currently, the `nir.__version__` does not seem to work. We should support that.

**Comment by biphasic** [comment]
for Sinabs and Tonic I'm using [pbr](https://docs.openstack.org/pbr/3.1.1/index.html) to automatically manage versions based on git tags. An option that I read about but have never tried is versioneer

**Comment by sheiksadique** [comment]
I suggest we use [setuptools-git-versioning](https://setuptools-git-versioning.readthedocs.io/en/v1.13.3/) tool for version management if we want to automate and do intermediate/pre releases. https://setuptools-git-versioning.readthedocs.io/en/v1.13.3/

**Comment by Jegp** [comment]
The latest PR #27 should add this to the `nir` package.

It uses the `dynamic` version number attribute in `pyproject.toml`, so the *only* place we have a version number is in the `__init__.py` file in the `nir` folder. 

I'm wondering if we should continue the discussion on release management. It would be nice to automate the release process. But then again, currently it's a simple matter of (a) bumping the version number and (b) creating a release. Is it worth improving? @biphasic @sheiksadique

**Comment by sheiksadique** [comment]
I am not certain how you typically deal with release management, so I can't comment about its complexity.

But there are essentially two places where the version is maintained still: 
1. the __init__.py file
2. git tag/version.

It is therefore possible in principle to have these two things out of sync.

There are essentially three advantages to automate the process of releases. 

1. There will be a unique location of version information.
2. The releases themselves can be automatically handled ie you do not need to create a separate release. A simple act of tagging should automate a major/minor release.
3. Any versions that are not explicitly tagged but pushed to the repos can still be published as pre-releases giving users immediate access to this without having to look up things in GitHub.

**Comment by Jegp** [comment]
Thanks for the comments @sheiksadique! I think you have very valid points, that would be worthy to treat in a separate issue: #48
