### ISSUE TITLE
Pull request checks failling because of failing lint of existing code in main

### ISSUE THREAD

**Issue by matjobst** [neuromorphs/NIR#31]
Currently, pull requests such as #30 are failing, because of Lint problems with existing code in main:
Error: example/nengo/nir-lorentz.py:182:89: E501 Line too long (94 > 88 characters)
Error: example/nengo/nir-test.py:67:89: E501 Line too long (94 > 88 characters)
Error: example/sinabs/import_to_sinabs.py:2:20: F401 `torch.nn` imported but unused
Error: example/sinabs/import_to_sinabs.py:3:25: F401 `sinabs.layers` imported but unused

I suggest locking the main branch from direct commits to enforce the use of pull requests along with the checks.

**Comment by sheiksadique** [comment]
This issue should be fixed now. But I agree about marking the main branch as protected.

**Comment by biphasic** [comment]
main branch is locked now, can only take up new commits through PRs. @sheiksadique you might want to check pre-commit as noted here https://github.com/neuromorphs/NIRTorch#for-developers
Will add a comment in the NIR readme too
