### ISSUE TITLE
Add tests for NIR edge dimensionality

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/NIR#4]
Every outgoing edge must have the same dimensionality as the corresponding incoming edge. We can ensure that by checking the edges when the `NIR` object is constructed. Perhaps by [`__post_init__`](https://docs.python.org/3/library/dataclasses.html#post-init-processing)?

**Comment by stevenabreu7** [comment]
the function for this is implemented in #59, which can be called on every graph. currently, it is not enforced, but this is suggested in PR #61 so I will close this issue
