### ISSUE TITLE
Discrepancy between Readme and docs on supported projects

### ISSUE THREAD

**Issue by jeremyforest** [neuromorphs/NIR#44]
In the Readme the section `Frameworks that currently support NIR` and in the doc `Supported simulators and hardware` show differences in write/read framework support. 

My guess would be that the Readme version is the most updated one ?

**Comment by jeremyforest** [comment]
Thanks @sheiksadique ! Should I leave this open until the doc is updated or do you want me to close it ?

**Comment by sheiksadique** [comment]
Please do leave it open so that we make sure to fix it asap.

**Comment by Jegp** [comment]
Thank you for pointing this out @jeremyforest ! I believe the discrepancy occurred because we counted Rockpool/Xylo and Sinabs/Speck separately. I'll submit at PR to rectify the issue and improve the wording.
