### ISSUE TITLE
Poor code design pattern for serializing/deserializing

### ISSUE THREAD

**Issue by sheiksadique** [neuromorphs/NIR#55]
At the moment, every primitive that needs to be added requires three different files to be modified. In particular the read and write methods are simply exceptionally long methods with if else conditions. 

The functionality of read write should be moved into the IR definitions so that things are better structured and modularised. This will also make things more scalable.

(We can take inspiration from the memento design pattern)

**Comment by Jegp** [comment]
That's a good point and a good idea. I wonder if we should also somehow split the ir file into smaller parts. If we add these functions, which, I think, is a good idea, it'll grow well beyond it's current ~500 lines  :scream:

**Comment by sheiksadique** [comment]
I would suggest we move each node to its own file. Easier to find and fix things in isolation hopefully.
