### ISSUE TITLE
meta-data in NIR nodes

### ISSUE THREAD

**Issue by stevenabreu7** [neuromorphs/NIR#70]
In our discussions, the idea came up to include metadata into NIR nodes that would help developers implement NIR nodes on their respective platform. 

As an example, @bvogginger pointed out in #63 that we should not include the reset mechanism into the NIR node definition itself, since the reset mechanism (subtractive, reset to zero, etc) is specific to digital implementations and has no place in the ODE formulation of the node. However, to make sure that NIR graphs commute across platforms, developers need to know what reset mechanism was originally implemented for a given NIR graph. Hence, the idea is to include a file of "metadata" into [every | some] NIR nodes that will give such relevant information. 

Suggestions for metadata:
- LIF/CubaLIF/IF/Threshold nodes: reset mechanism used (e.g. reset-to-zero, subtractive-reset), output spike types used (e.g. graded or not graded - this then also influences the reset mechanism), time step used (for discretization)

**Comment by sheiksadique** [comment]
Thought: A big risk of adding this meta data is libraries getting dependent on this data. This can quickly go downhill from there.

**Comment by Jegp** [comment]
Closed with #79

**Comment by Jegp** [comment]
> Thought: A big risk of adding this meta data is libraries getting dependent on this data. This can quickly go downhill from there.

I added [a warning on this in the docs](https://nnir.readthedocs.io/en/latest/primitives.html#metadata). But yes, this is a big danger we should be concerned and aware about going forward
