### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by Tobias-Fischer** [neuromorphs/NIR#74]
Hiya,

Thanks a lot for NIR, it's very cool work.

The pyproject.toml specifies the license as Apache (https://github.com/neuromorphs/NIR/blob/416e8c20288322ea0bef7fec4615aa74723d6c0d/pyproject.toml#L22) but the LICENSE file states BSD. Could you please clarify and amend accordingly?

Many thanks,
Tobi

PS: Background - I'd like to package NIR on conda-forge.

**Comment by Jegp** [comment]
Thank you for pointing this out. The license should be BSD-3. The pyproject.toml should be updated. Do you require a release as well to get this working on conda?

Btw a neat idea. Please let us know if we can help :)

**Comment by Tobias-Fischer** [comment]
A release would be amazing, many thanks :)

**Comment by Jegp** [comment]
New release is live (v1.0.1) :partying_face:
